development:
  adapter: postgresql
  encoding: utf8
  database: chat_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: chat_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: chat_production
  pool: 5
  username: 
  password:

cucumber:
  <<: *TEST

default: &default
  host: localhost
